# Generated by Django 4.2.20 on 2025-04-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_file_hash_file_is_duplicate_file_original_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='duplicate_count',
            field=models.IntegerField(default=0),
        ),
    ]
